### ISSUE TITLE
unrecognized selector sent to instance

### ISSUE THREAD

**Issue by MassRootsAdam** [updatezen/PFCloud-Cache#7]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PFObject encodeWithCoder:]: unrecognized selector sent to instance 0x170139aa0'

I'm getting the error message above. Could you please help me address this issue?

**Comment by Vaberer** [comment]
Hello, I have the same problem. How did you solve this issue?

Thanks
